# Generated by Django 3.1 on 2020-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200806_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/blank-profile.png', upload_to='images/'),
        ),
    ]
